name: CI

on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "${{ github.GITHUB_REPOSITORY }}-server"
          curl "https://demo.polaris.synopsys.com/api/tools/polaris_cli-linux64.zip"
          unzip -d /tmp -jo polaris_cli-linux64.zip
          /tmp/polaris analyze -w -- make build
